name: ginForBHDeploy
on:
  push:
    branches:
      - master
    tags:
      -v*
  pull_request:
    branches:
      - master
    types: [closed]
        
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy To Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: bash /home/cunoe/run.sh
